name: Build and deploy GH pages site

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write
  
# Controls when the workflow will run
on:
  push:
    branches:
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install deps
        run: npm i

      - name: Build site source
        run: npm run build

      - name: Build tar for github pages
        run: tar --dereference --hard-dereference --directory public/ -cvf artifact.tar .

      - name: Upload tar for github pages
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
