name: Build and deploy GH pages site

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'  # speeds up CI builds

      - name: Install dependencies
        run: npm ci  # safer & faster than `npm i` in CI

      - name: Build site source
        run: npm run build

      - name: Create tar for GitHub Pages
        run: tar --dereference --hard-dereference --directory public/ -cvf artifact.tar .

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v4  # use stable version
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
